version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/nextjs-app/

hooks:
  AfterInstall:
    - location: scripts/clean_up.sh
      timeout: 300
      runas: root
  ApplicationStart: 
    - location: scripts/start_server.sh
      timeout: 300
      runas: root