name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.15

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: nextjs-build
        path: |
          .next/
          node_modules/
          public/
          package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: nextjs-build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Copy files to S3
      run: aws s3 cp ./nextjs-build/ s3://${{ secrets.S3_BUCKET_NAME }}/ --recursive

    - name: Deploy to EC2 using CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
          --deployment-group-name ${{ secrets.CODEDEPLOY_GROUP_NAME }} \
          --revision location=s3,s3Location={bucket=${{ secrets.S3_BUCKET_NAME }},key=nextjs-build,bundleType=zip} \
          --deployment-config-name CodeDeployDefault.OneAtATime